CREATE TABLE "event_sync_status" (
	"id" serial PRIMARY KEY NOT NULL,
	"connector" varchar(50) NOT NULL,
	"last_synced_at" timestamp,
	"last_successful_sync_at" timestamp,
	"sync_status" varchar(50) DEFAULT 'idle',
	"error_message" text,
	"events_processed" integer DEFAULT 0,
	"events_created" integer DEFAULT 0,
	"events_updated" integer DEFAULT 0,
	"events_skipped" integer DEFAULT 0,
	"next_sync_scheduled_at" timestamp,
	"sync_duration_ms" integer,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "event_sync_status_connector_unique" UNIQUE("connector")
);
--> statement-breakpoint
CREATE TABLE "uk_events" (
	"id" serial PRIMARY KEY NOT NULL,
	"external_id" varchar(255) NOT NULL,
	"source" varchar(50) NOT NULL,
	"title" varchar(512) NOT NULL,
	"description" text,
	"category" varchar(100),
	"subcategory" varchar(100),
	"event_date" timestamp NOT NULL,
	"doors_time" timestamp,
	"venue" varchar(255) NOT NULL,
	"city" varchar(100) NOT NULL,
	"latitude" numeric(10, 8),
	"longitude" numeric(11, 8),
	"image_url" varchar(512),
	"ticket_url" varchar(512),
	"ticket_status" varchar(50),
	"price_min" numeric(10, 2),
	"price_max" numeric(10, 2),
	"currency" varchar(3) DEFAULT 'GBP',
	"artists" text,
	"age_restriction" varchar(50),
	"is_featured" boolean DEFAULT false,
	"is_synced" boolean DEFAULT true,
	"last_synced_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "uk_events_external_id_unique" UNIQUE("external_id")
);
