CREATE TABLE `analytics_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`event` varchar(80) NOT NULL,
	`path` varchar(512),
	`referrer` varchar(512),
	`userAgent` varchar(512),
	`ipHash` varchar(64),
	`props` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `analytics_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_recommendations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`eventId` int NOT NULL,
	`userId` int,
	`recommenderName` varchar(255),
	`recommenderEmail` varchar(255),
	`reason` text NOT NULL,
	`upvotes` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `event_recommendations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `event_sync_status` (
	`id` int AUTO_INCREMENT NOT NULL,
	`source` varchar(50) NOT NULL,
	`last_synced_at` timestamp NOT NULL,
	`events_found` int DEFAULT 0,
	`events_added` int DEFAULT 0,
	`events_updated` int DEFAULT 0,
	`status` enum('success','partial','failed') DEFAULT 'success',
	`error_message` text,
	`created_at` timestamp DEFAULT (now()),
	CONSTRAINT `event_sync_status_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `promoter_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`name` varchar(255) NOT NULL,
	`companyName` varchar(255),
	`email` varchar(255) NOT NULL,
	`phone` varchar(20),
	`website` varchar(512),
	`instagramHandle` varchar(100),
	`twitterHandle` varchar(100),
	`facebookUrl` varchar(512),
	`isVerified` boolean NOT NULL DEFAULT false,
	`verifiedAt` timestamp,
	`verificationNotes` text,
	`totalEventsSubmitted` int NOT NULL DEFAULT 0,
	`approvedEventsCount` int NOT NULL DEFAULT 0,
	`bio` text,
	`logoUrl` varchar(512),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `promoter_profiles_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `uk_events` (
	`id` int AUTO_INCREMENT NOT NULL,
	`external_id` varchar(255) NOT NULL,
	`source` enum('ticketmaster','stubhub','eventbrite','skiddle','dice','user_submission') NOT NULL,
	`title` varchar(500) NOT NULL,
	`description` text,
	`category` enum('music','festival','boxing','sports','comedy','theatre','clubbing','other') NOT NULL,
	`subcategory` varchar(100),
	`genre` varchar(100),
	`venue_name` varchar(255),
	`venue_address` varchar(500),
	`city` varchar(100) NOT NULL,
	`postcode` varchar(20),
	`latitude` varchar(20),
	`longitude` varchar(20),
	`event_date` timestamp NOT NULL,
	`event_end_date` timestamp,
	`doors_time` varchar(10),
	`image_url` varchar(512),
	`thumbnail_url` varchar(512),
	`ticket_url` varchar(512),
	`price_min` varchar(50),
	`price_max` varchar(50),
	`currency` varchar(10) DEFAULT 'GBP',
	`ticket_status` enum('available','limited','sold_out','cancelled','postponed') DEFAULT 'available',
	`artists` json,
	`age_restriction` varchar(50),
	`is_featured` boolean NOT NULL DEFAULT false,
	`is_verified` boolean NOT NULL DEFAULT true,
	`view_count` int NOT NULL DEFAULT 0,
	`last_synced_at` timestamp NOT NULL DEFAULT (now()),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `uk_events_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user_event_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int,
	`submitterName` varchar(255) NOT NULL,
	`submitterEmail` varchar(255) NOT NULL,
	`submitterPhone` varchar(20),
	`isPromoter` boolean NOT NULL DEFAULT false,
	`promoterId` int,
	`title` varchar(500) NOT NULL,
	`description` text NOT NULL,
	`category` enum('music','festival','boxing','sports','comedy','theatre','clubbing','other') NOT NULL,
	`subcategory` varchar(100),
	`genre` varchar(100),
	`venueName` varchar(255) NOT NULL,
	`venueAddress` varchar(500),
	`city` varchar(100) NOT NULL,
	`postcode` varchar(20),
	`eventDate` timestamp NOT NULL,
	`eventEndDate` timestamp,
	`doorsTime` varchar(10),
	`imageUrl` varchar(512),
	`ticketUrl` varchar(512),
	`priceMin` varchar(50),
	`priceMax` varchar(50),
	`artists` text,
	`ageRestriction` varchar(50),
	`additionalNotes` text,
	`status` enum('pending','approved','rejected','needs_info') NOT NULL DEFAULT 'pending',
	`reviewedBy` int,
	`reviewedAt` timestamp,
	`rejectionReason` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `user_event_submissions_id` PRIMARY KEY(`id`)
);
