/**
 * Auto Promo Engine - Generates promo clips, subtitles, thumbnails
 * Uses real AI providers when available
 */

import { chatCompletion } from "./aiProviders";
import { dannyPersona } from "./dannyPersona";

export type PromoType = "clip" | "subtitle" | "thumbnail" | "post";
export type SourceType = "mix" | "show" | "shout" | "reaction";

export interface PromoRequest {
  type: PromoType;
  sourceType: SourceType;
  sourceId: number;
  sourceData?: any;
}

export interface GeneratedPromo {
  content: string;
  mediaUrl?: string;
  thumbnailUrl?: string;
}

/**
 * Generate promo content
 * Uses AI to generate engaging promotional content
 */
export async function generatePromoContent(request: PromoRequest): Promise<GeneratedPromo> {
  const { type, sourceType, sourceData } = request;

  if (type === "post") {
    const prompt = `Generate a social media post for a ${sourceType}:
${sourceData?.title ? `Title: ${sourceData.title}` : ""}
${sourceData?.name ? `Name: ${sourceData.name}` : ""}
${sourceData?.message ? `Message: ${sourceData.message.substring(0, 200)}` : ""}

Make it engaging, in Danny Hectic B's style, with emojis and hashtags. Keep it concise (2-3 sentences max).`;

    try {
      const aiResponse = await chatCompletion({
        messages: [
          {
            role: "system",
            content: dannyPersona.systemPrompt + "\n\nYou are generating social media promotional posts. Be engaging, energetic, and authentic.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        persona: "Danny Hectic B",
      });

      return {
        content: aiResponse.text,
      };
    } catch (error) {
      console.error("[AI Promo] Failed to generate promo:", error);
    }
  }
  
  let content = "";
  
  if (type === "post") {
    if (sourceType === "mix") {
      content = `🔥 NEW MIX ALERT! 🔥\n\nJust dropped "${sourceData?.title || "a fire mix"}" on Hectic Radio! Lock in and vibe with the crew!\n\n🎵 Full mix available now\n💥 Track selection is fire\n🔥 Don't sleep on this one\n\n#HecticRadio #DJDannyHecticB #NewMix`;
    } else if (sourceType === "show") {
      content = `📻 LIVE NOW! 📻\n\n${sourceData?.name || "Hectic Radio"} is on air! Tune in now and lock in with the crew!\n\n🎧 Live streaming\n🔥 Fire tracks incoming\n💥 Big shouts coming up\n\n#HecticRadio #LiveNow #DJDannyHecticB`;
    } else if (sourceType === "shout") {
      content = `Big up to ${sourceData?.name || "the crew"} for the fire shout! 🔥\n\n"${sourceData?.message?.substring(0, 100) || "Locked in!"}"\n\nYou're part of the Hectic Radio family! 💪\n\n#HecticRadio #ShoutOut #LockedIn`;
    } else if (sourceType === "reaction") {
      content = `Danny Reacts! 🔥\n\nJust checked out ${sourceData?.title || "this submission"} and I'm feeling it! ${sourceData?.aiReaction?.substring(0, 150) || "This is fire!"}\n\n#DannyReacts #HecticRadio`;
    }
  } else if (type === "subtitle") {
    content = sourceData?.title || "Hectic Radio - Lock In";
  } else if (type === "clip") {
    content = "Promo clip for: " + (sourceData?.title || "content");
  } else if (type === "thumbnail") {
    content = "Thumbnail for: " + (sourceData?.title || "content");
  }
  
  return {
    content,
    // mediaUrl and thumbnailUrl would be generated by actual AI/media processing
  };
}

