#!/usr/bin/env bash
# ai-triage.sh: AI-powered CI failure triage (Ollama-based, optional)
# Usage: ./scripts/ai-triage.sh [CI_LOG_FILE] [PR_NUMBER]
set -euo pipefail

CI_LOG_FILE="${1:-/dev/stdin}"
PR_NUMBER="${2:-}"

# Configuration
OLLAMA_HOST="${OLLAMA_HOST:-http://localhost:11434}"
MODEL="${OLLAMA_MODEL:-qwen2.5:7b}"

echo "🤖 AI Triage: Analyzing CI failure..."

# Check if Ollama is available
if ! curl -s "${OLLAMA_HOST}/api/tags" > /dev/null 2>&1; then
  echo "⚠️  Ollama not available at ${OLLAMA_HOST}"
  echo "   Install: curl -fsSL https://ollama.com/install.sh | sh"
  echo "   Start: ollama serve"
  echo "   Pull model: ollama pull ${MODEL}"
  exit 0
fi

# Read CI log
if [ "$CI_LOG_FILE" = "/dev/stdin" ]; then
  CI_LOG=$(cat)
else
  CI_LOG=$(cat "$CI_LOG_FILE")
fi

# Truncate if too long (keep last 5000 chars for context)
if [ ${#CI_LOG} -gt 5000 ]; then
  CI_LOG="${CI_LOG: -5000}"
fi

# Create prompt
PROMPT="You are a senior software engineer reviewing CI/CD failures. Analyze this CI log and provide:

1. Root Cause: What failed and why (1-2 sentences)
2. Fix Steps: Specific actions to resolve (3-5 bullet points)
3. Risk: Impact if not fixed (1 sentence)

Be concise and actionable. Format as markdown.

CI Log:
\`\`\`
${CI_LOG}
\`\`\`"

# Call Ollama API
echo "  Calling Ollama ${MODEL}..."
RESPONSE=$(curl -s "${OLLAMA_HOST}/api/generate" \
  -d "{
    \"model\": \"${MODEL}\",
    \"prompt\": \"${PROMPT}\",
    \"stream\": false
  }" | jq -r '.response')

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🤖 AI Triage Analysis"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "$RESPONSE"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# If PR number provided and GH_TOKEN available, post as comment
if [ -n "$PR_NUMBER" ] && [ -n "${GH_TOKEN:-}" ]; then
  echo ""
  echo "📝 Posting to PR #${PR_NUMBER}..."
  
  COMMENT_BODY="## 🤖 AI Triage: CI Failure Analysis

${RESPONSE}

---
*Generated by Ollama ${MODEL} | [Logs](https://github.com/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)*"
  
  gh pr comment "$PR_NUMBER" --body "$COMMENT_BODY" || {
    echo "⚠️  Failed to post comment (check GH_TOKEN)"
  }
fi

echo ""
echo "✅ AI triage complete"
