/**
 * UK Events Seed Script
 * Seeds demo UK events for testing
 * 
 * Run with: npx tsx scripts/seed_uk_events.ts
 */

// Demo events data - realistic UK music/boxing/festival events
const demoEvents = [
    {
        externalId: 'demo-001',
        source: 'ticketmaster' as const,
        title: 'GARAGE NATION: THE RETURN',
        description: 'The legendary Garage Nation returns! Featuring the biggest names in UK Garage, bringing back the golden era vibes with a modern twist. Expect to hear classics alongside fresh cuts from the scene\'s finest.',
        category: 'music' as const,
        subcategory: 'UK Garage',
        genre: 'UK Garage',
        venueName: 'Printworks London',
        venueAddress: 'Surrey Quays Rd',
        city: 'London',
        postcode: 'SE16 7PJ',
        latitude: '51.4925',
        longitude: '-0.0487',
        eventDate: new Date('2024-03-15T21:00:00Z'),
        eventEndDate: new Date('2024-03-16T06:00:00Z'),
        doorsTime: '21:00',
        imageUrl: 'https://images.unsplash.com/photo-1571266028243-d220c6a8583c?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1571266028243-d220c6a8583c?w=400&q=80',
        ticketUrl: 'https://www.ticketmaster.co.uk',
        priceMin: '35.00',
        priceMax: '75.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['DJ EZ', 'Todd Edwards', 'Wookie', 'Sticky', 'Artful Dodger']),
        ageRestriction: '18+',
        isFeatured: true,
        isVerified: true,
    },
    {
        externalId: 'demo-002',
        source: 'ticketmaster' as const,
        title: 'TYSON FURY vs OLEKSANDR USYK II',
        description: 'The rematch the world has been waiting for! Undisputed Heavyweight Championship on the line as The Gypsy King faces The Cat in an epic showdown for boxing supremacy.',
        category: 'boxing' as const,
        subcategory: 'Heavyweight Boxing',
        genre: null,
        venueName: 'Wembley Stadium',
        venueAddress: 'Wembley',
        city: 'London',
        postcode: 'HA9 0WS',
        latitude: '51.5561',
        longitude: '-0.2795',
        eventDate: new Date('2024-04-20T18:00:00Z'),
        eventEndDate: new Date('2024-04-21T00:00:00Z'),
        doorsTime: '17:00',
        imageUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?w=400&q=80',
        ticketUrl: 'https://www.ticketmaster.co.uk',
        priceMin: '150.00',
        priceMax: '1500.00',
        currency: 'GBP',
        ticketStatus: 'limited' as const,
        artists: JSON.stringify(['Tyson Fury', 'Oleksandr Usyk']),
        ageRestriction: null,
        isFeatured: true,
        isVerified: true,
    },
    {
        externalId: 'demo-003',
        source: 'eventbrite' as const,
        title: 'DIMENSIONS FESTIVAL 2024',
        description: 'The ultimate underground electronic music festival returns to Croatia! Five days of cutting-edge house, techno, disco, and drum & bass in a stunning fortress setting.',
        category: 'festival' as const,
        subcategory: 'Electronic Music Festival',
        genre: 'House / Techno',
        venueName: 'Fort Punta Christo',
        venueAddress: 'Pula',
        city: 'Pula (UK Flights)',
        postcode: null,
        latitude: '44.8666',
        longitude: '13.8496',
        eventDate: new Date('2024-08-28T14:00:00Z'),
        eventEndDate: new Date('2024-09-01T12:00:00Z'),
        doorsTime: null,
        imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=400&q=80',
        ticketUrl: 'https://www.dimensionsfestival.com',
        priceMin: '189.00',
        priceMax: '349.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Four Tet', 'Ben UFO', 'Goldie', 'DJ Stingray', 'Mall Grab']),
        ageRestriction: '18+',
        isFeatured: true,
        isVerified: true,
    },
    {
        externalId: 'demo-004',
        source: 'dice' as const,
        title: 'FABRIC: HESSLE AUDIO TAKEOVER',
        description: 'Hessle Audio takes the reins at fabric for one of their legendary takeovers. Bass weight guaranteed from midnight till the sun comes up.',
        category: 'clubbing' as const,
        subcategory: 'Bass / Dubstep',
        genre: 'Bass Music',
        venueName: 'fabric London',
        venueAddress: '77A Charterhouse St',
        city: 'London',
        postcode: 'EC1M 6HJ',
        latitude: '51.5199',
        longitude: '-0.1024',
        eventDate: new Date('2024-03-22T23:00:00Z'),
        eventEndDate: new Date('2024-03-23T07:00:00Z'),
        doorsTime: '23:00',
        imageUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&q=80',
        ticketUrl: 'https://www.dice.fm',
        priceMin: '25.00',
        priceMax: '35.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Ben UFO', 'Pearson Sound', 'Pangaea']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-005',
        source: 'stubhub' as const,
        title: 'CRAIG DAVID TS5 LIVE',
        description: 'Craig David brings his legendary TS5 party to Manchester! Expect garage classics, R&B anthems, and non-stop party vibes from one of the UK\'s greatest artists.',
        category: 'music' as const,
        subcategory: 'UK Garage / R&B',
        genre: 'UK Garage',
        venueName: 'O2 Victoria Warehouse',
        venueAddress: 'Trafford Wharf Road',
        city: 'Manchester',
        postcode: 'M17 1AB',
        latitude: '53.4630',
        longitude: '-2.2837',
        eventDate: new Date('2024-04-05T19:00:00Z'),
        eventEndDate: new Date('2024-04-05T23:00:00Z'),
        doorsTime: '18:00',
        imageUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?w=400&q=80',
        ticketUrl: 'https://www.stubhub.co.uk',
        priceMin: '45.00',
        priceMax: '85.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Craig David']),
        ageRestriction: '16+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-006',
        source: 'skiddle' as const,
        title: 'HOSPITALITY IN THE PARK 2024',
        description: 'The UK\'s biggest drum & bass event returns to Finsbury Park! 40,000 bass heads, 6 stages, and the best DnB artists on the planet.',
        category: 'festival' as const,
        subcategory: 'Drum & Bass',
        genre: 'Drum & Bass',
        venueName: 'Finsbury Park',
        venueAddress: 'Endymion Road',
        city: 'London',
        postcode: 'N4 2NQ',
        latitude: '51.5648',
        longitude: '-0.1066',
        eventDate: new Date('2024-09-14T12:00:00Z'),
        eventEndDate: new Date('2024-09-14T22:00:00Z'),
        doorsTime: '12:00',
        imageUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400&q=80',
        ticketUrl: 'https://www.skiddle.com',
        priceMin: '50.00',
        priceMax: '95.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['High Contrast', 'Friction', 'Metrik', 'Camo & Krooked', 'Sub Focus', 'Dimension']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-007',
        source: 'ticketmaster' as const,
        title: 'NOTTING HILL CARNIVAL WARM-UP',
        description: 'Get ready for Carnival! The ultimate pre-Carnival party featuring the best in Soca, Dancehall, Afrobeats, and UK vibes.',
        category: 'music' as const,
        subcategory: 'Soca / Afrobeats',
        genre: 'Afrobeats',
        venueName: 'Brixton Academy',
        venueAddress: '211 Stockwell Rd',
        city: 'London',
        postcode: 'SW9 9SL',
        latitude: '51.4652',
        longitude: '-0.1153',
        eventDate: new Date('2024-08-23T21:00:00Z'),
        eventEndDate: new Date('2024-08-24T04:00:00Z'),
        doorsTime: '21:00',
        imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&q=80',
        ticketUrl: 'https://www.ticketmaster.co.uk',
        priceMin: '30.00',
        priceMax: '60.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Major Lazer', 'Stylo G', 'Ding Dong']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-008',
        source: 'eventbrite' as const,
        title: 'MICHAEL MCINTYRE: SHOWTIME!',
        description: 'The UK\'s favourite comedian returns with his brand new show! Laugh until it hurts with Michael\'s hilarious observations on modern life.',
        category: 'comedy' as const,
        subcategory: 'Stand-up Comedy',
        genre: null,
        venueName: 'The O2',
        venueAddress: 'Peninsula Square',
        city: 'London',
        postcode: 'SE10 0DX',
        latitude: '51.5033',
        longitude: '0.0032',
        eventDate: new Date('2024-05-10T19:30:00Z'),
        eventEndDate: new Date('2024-05-10T22:00:00Z'),
        doorsTime: '18:30',
        imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=400&q=80',
        ticketUrl: 'https://www.eventbrite.co.uk',
        priceMin: '55.00',
        priceMax: '125.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Michael McIntyre']),
        ageRestriction: null,
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-009',
        source: 'ticketmaster' as const,
        title: 'BOILER ROOM x DEKMANTEL',
        description: 'Boiler Room and Dekmantel join forces for an exclusive London session. Intimate vibes, world-class selectors, no nonsense.',
        category: 'clubbing' as const,
        subcategory: 'Techno / House',
        genre: 'Techno',
        venueName: 'Corsica Studios',
        venueAddress: '5 Elephant Road',
        city: 'London',
        postcode: 'SE17 1LB',
        latitude: '51.4937',
        longitude: '-0.1008',
        eventDate: new Date('2024-03-29T22:00:00Z'),
        eventEndDate: new Date('2024-03-30T06:00:00Z'),
        doorsTime: '22:00',
        imageUrl: 'https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1598387993281-cecf8b71a8f8?w=400&q=80',
        ticketUrl: 'https://boilerroom.tv',
        priceMin: '20.00',
        priceMax: '25.00',
        currency: 'GBP',
        ticketStatus: 'limited' as const,
        artists: JSON.stringify(['Hunee', 'Palms Trax', 'Jayda G']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-010',
        source: 'dice' as const,
        title: 'JUNGLE MANIA WEEKENDER',
        description: 'The original jungle massive returns for a full weekend of classic breaks and amen vibes. Old school raving at its finest.',
        category: 'music' as const,
        subcategory: 'Jungle',
        genre: 'Jungle',
        venueName: 'Motion Bristol',
        venueAddress: '74-78 Avon Street',
        city: 'Bristol',
        postcode: 'BS2 0PX',
        latitude: '51.4446',
        longitude: '-2.5871',
        eventDate: new Date('2024-06-07T22:00:00Z'),
        eventEndDate: new Date('2024-06-09T06:00:00Z'),
        doorsTime: '22:00',
        imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400&q=80',
        ticketUrl: 'https://www.dice.fm',
        priceMin: '40.00',
        priceMax: '80.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Congo Natty', 'General Levy', 'DJ Zinc', 'Kenny Ken']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-011',
        source: 'stubhub' as const,
        title: 'PREMIER LEAGUE: ARSENAL vs MANCHESTER CITY',
        description: 'A potential title decider at the Emirates! The Gunners face the reigning champions in what promises to be a blockbuster encounter.',
        category: 'sports' as const,
        subcategory: 'Football',
        genre: null,
        venueName: 'Emirates Stadium',
        venueAddress: 'Hornsey Rd',
        city: 'London',
        postcode: 'N7 7AJ',
        latitude: '51.5549',
        longitude: '-0.1085',
        eventDate: new Date('2024-04-28T16:30:00Z'),
        eventEndDate: new Date('2024-04-28T18:30:00Z'),
        doorsTime: '14:00',
        imageUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1489944440615-453fc2b6a9a9?w=400&q=80',
        ticketUrl: 'https://www.stubhub.co.uk',
        priceMin: '95.00',
        priceMax: '450.00',
        currency: 'GBP',
        ticketStatus: 'limited' as const,
        artists: null,
        ageRestriction: null,
        isFeatured: false,
        isVerified: true,
    },
    {
        externalId: 'demo-012',
        source: 'skiddle' as const,
        title: 'AMAPIANO UNCUT: SUMMER EDITION',
        description: 'The hottest Amapiano party in the UK! South African vibes meet London energy. Expect log drum rhythms, deep bass, and endless dance floors.',
        category: 'music' as const,
        subcategory: 'Amapiano',
        genre: 'Amapiano',
        venueName: 'Village Underground',
        venueAddress: '54 Holywell Lane',
        city: 'London',
        postcode: 'EC2A 3PQ',
        latitude: '51.5254',
        longitude: '-0.0787',
        eventDate: new Date('2024-07-13T22:00:00Z'),
        eventEndDate: new Date('2024-07-14T05:00:00Z'),
        doorsTime: '22:00',
        imageUrl: 'https://images.unsplash.com/photo-1504680177321-2e6a879aac86?w=800&q=80',
        thumbnailUrl: 'https://images.unsplash.com/photo-1504680177321-2e6a879aac86?w=400&q=80',
        ticketUrl: 'https://www.skiddle.com',
        priceMin: '20.00',
        priceMax: '35.00',
        currency: 'GBP',
        ticketStatus: 'available' as const,
        artists: JSON.stringify(['Uncle Waffles', 'Major League DJz', 'DBN Gogo']),
        ageRestriction: '18+',
        isFeatured: false,
        isVerified: true,
    },
];

console.log('--------------------------------------------');
console.log(' UK EVENTS SEED DATA');
console.log(' Copy these events into your database');
console.log('--------------------------------------------');
console.log('');
console.log('Total demo events:', demoEvents.length);
console.log('');
console.log('Categories:');
const categories: Record<string, number> = {};
demoEvents.forEach(e => {
    categories[e.category] = (categories[e.category] || 0) + 1;
});
Object.entries(categories).forEach(([cat, count]) => {
    console.log(`  - ${cat}: ${count}`);
});
console.log('');
console.log('Featured events:', demoEvents.filter(e => e.isFeatured).length);
console.log('');
console.log('Export for SQL insertion:');
console.log(JSON.stringify(demoEvents, null, 2));
