name: Monorepo CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Runner Status
        run: echo "Self-hosted runner is successfully processing the job!"
